# Use a base Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /app/payment-service

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 8084

# Command to run the application
CMD ["node", "server.js"]
